version: '3.7'

services:

  frontend:
    container_name: frontend
    build: 
      context: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true